model:
  latent_dim: 2048
  proj_dropout: 0.1
  linear_projection: true
  model_path: "roberta-base"
  model_arch: "roberta"
  encoder_type: "MLMSumEncoder"
  grad_clip: -1.0
  momentum: 0.0
  device: "cuda"

train_job:
  n_ctx: 512
  epochs: 10
  batch_size: 64
  microbatch_size: 1
  lr_ramp_steps: 400
  lr_decay_steps: 3366
  learning_rate_init: 1.0e-4
  learning_rate_target: 0.000006
  log_interval: 2
  checkpoint_interval: 50
  validate_interval: 50
  use_half: false
  do_log: true
  validation_size: 1000
  eval_selection: "final_n"
  use_bucket: false
  dupe_protection: true
  hard_dupe_protection: false
  data_pipeline: "MLMDataPipeline"
  orchestrator: "BaseOrchestrator"
  